server:
  port: 8089
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: authentication-service
          uri: lb://authentication-service
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - AuthenticationFilter

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA-URI:http://localhost:8762/eureka}
  instance:
    prefer-ip-address: true

